export default defineAppConfig({
  pages: [
    "pages/my/index",
    "pages/splash/index",
    "pages/home/index",
    "pages/category/index",
    "pages/cart/index",
    "pages/product-detail/index",
  ],
  subPackages: [
    {
      root: "pages-sub",
      pages: [
        "series-detail/index",
        "series-promotion/index",
        "payment/index",
        "payment-failed/index",
        "payment-select-address/index",
        "register/index",
        "edit-info/index",
        "address-list/index",
        "address-edit/index",
        "order-list/index",
        "after-sales/index",
        "after-sales-detail/index",
        "refund/index",
        "return-exchange-detail/index",
        "reservation/index",
        "reservation-normal/index",
        "reservation-change/index",
        "reservation-success/index",
        "reservation-easy/index",
        "wishlist/index",
        "consultation/index",
        "privacy-policy/index",
        "user-agreement/index",
        "product-cms/index",
      ],
    },
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "YZHENG",
    navigationBarTextStyle: "black",
    navigationStyle: "custom",
  },
  tabBar: {
    custom: true,
    color: "#999999",
    selectedColor: "#000000",
    backgroundColor: "#ffffff",
    list: [
      { pagePath: "pages/home/index", text: "首页" },
      { pagePath: "pages/category/index", text: "分类" },
      { pagePath: "pages/cart/index", text: "购物车" },
      { pagePath: "pages/my/index", text: "我的" },
    ],
  },
});
